"""Constants for the layout of the application."""

NUM_ROWS = 7
NUM_COLS = 6

LOGO_ROW = 0
LOGO_COL = 0
LOGO_ROW_SPAN = 2
LOGO_COL_SPAN = 6

JOB_ATTR_BANNER_ROW = 1
JOB_ATTR_BANNER_COL = 0
JOB_ATTR_BANNER_ROW_SPAN = 1
JOB_ATTR_BANNER_COL_SPAN = 6

JOB_DISPLAY_ROW = 2
JOB_DISPLAY_COL = 0
JOB_DISPLAY_ROW_SPAN = 3
JOB_DISPLAY_COL_SPAN = 6

KILL_ALL_BUTTON_ROW = 5
KILL_ALL_BUTTON_COL = 3
KILL_ALL_BUTTON_ROW_SPAN = 1
KILL_ALL_BUTTON_COL_SPAN = 1

HOLD_ALL_BUTTON_ROW = 5
HOLD_ALL_BUTTON_COL = 4
HOLD_ALL_BUTTON_ROW_SPAN = 1
HOLD_ALL_BUTTON_COL_SPAN = 1

RELEASE_ALL_BUTTON_ROW = 6
RELEASE_ALL_BUTTON_COL = 4
RELEASE_ALL_BUTTON_ROW_SPAN = 1
RELEASE_ALL_BUTTON_COL_SPAN = 1

REFRESH_BUTTON_ROW = 6
REFRESH_BUTTON_COL = 3
REFRESH_BUTTON_ROW_SPAN = 1
REFRESH_BUTTON_COL_SPAN = 1

FILTER_ATTRIBUTE_INPUT_ROW = 5
FILTER_ATTRIBUTE_INPUT_COL = 1
FILTER_ATTRIBUTE_INPUT_ROW_SPAN = 1
FILTER_ATTRIBUTE_INPUT_COL_SPAN = 2

FILTER_REGEX_INPUT_ROW = 6
FILTER_REGEX_INPUT_COL = 1
FILTER_REGEX_INPUT_ROW_SPAN = 1
FILTER_REGEX_INPUT_COL_SPAN = 2
